name: FlashingFireworks
author: InfernoSpirit
main: me.InfernoSpirit.FlashingFireworks.MainClass
version: 2.0.0
commands:
  flashingfireworks:
    description: Main commands for FlashingFireworks.
    usage: /<command>
  ff:
    description: Main commands for FlashingFireworks.
    usage: /<command>