name: FFireworksX
author: garrettsummerfi3ld
authors:
  - InfernoSpirit
main: io.garrettsummerfi3ld.ffireworksx.Main
version: 0.0.1
commands:
  flashingfireworks:
    description: Main commands for FFireworksX.
    usage: /<command>
  ff:
    description: Main commands for FFireworks.
    usage: /<command>